### ISSUE TITLE
Server Error after deployment

### ISSUE THREAD

**Issue by Shrimad-Bhagwat** [Shrimad-Bhagwat/Article-Zone#2]
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
![image](https://user-images.githubusercontent.com/51125208/134396753-970a14ed-2119-41b4-8874-83e374734fa9.png)

**Comment by Shrimad-Bhagwat** [comment]
$ heroku logs --tail
2021-09-22T17:57:23.992798+00:00 app[web.1]: syslog: False
2021-09-22T17:57:23.992798+00:00 app[web.1]: syslog_prefix: None
2021-09-22T17:57:23.992798+00:00 app[web.1]: syslog_facility: user
2021-09-22T17:57:23.992798+00:00 app[web.1]: enable_stdio_inheritance: False
2021-09-22T17:57:23.992799+00:00 app[web.1]: statsd_host: None
2021-09-22T17:57:23.992799+00:00 app[web.1]: dogstatsd_tags:
2021-09-22T17:57:23.992799+00:00 app[web.1]: statsd_prefix:
2021-09-22T17:57:23.992799+00:00 app[web.1]: proc_name: None
2021-09-22T17:57:23.992799+00:00 app[web.1]: default_proc_name: main:app
2021-09-22T17:57:23.992799+00:00 app[web.1]: pythonpath: None
2021-09-22T17:57:23.992800+00:00 app[web.1]: paste: None
2021-09-22T17:57:23.992800+00:00 app[web.1]: on_starting: <function OnStarting.on_starting at 0x7f19317e39d0>
2021-09-22T17:57:23.992800+00:00 app[web.1]: on_reload: <function OnReload.on_reload at 0x7f19317e3af0>
2021-09-22T17:57:23.992801+00:00 app[web.1]: when_ready: <function WhenReady.when_ready at 0x7f19317e3c10>
2021-09-22T17:57:23.992801+00:00 app[web.1]: pre_fork: <function Prefork.pre_fork at 0x7f19317e3d30>
2021-09-22T17:57:23.992801+00:00 app[web.1]: post_fork: <function Postfork.post_fork at 0x7f19317e3e50>
2021-09-22T17:57:23.992801+00:00 app[web.1]: post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f19317e3f70>
2021-09-22T17:57:23.992802+00:00 app[web.1]: worker_int: <function WorkerInt.worker_int at 0x7f1931b9e0d0>
2021-09-22T17:57:23.992802+00:00 app[web.1]: worker_abort: <function WorkerAbort.worker_abort at 0x7f1931b9e1f0>
2021-09-22T17:57:23.992802+00:00 app[web.1]: pre_exec: <function PreExec.pre_exec at 0x7f1931b9e310>
2021-09-22T17:57:23.992802+00:00 app[web.1]: pre_request: <function PreRequest.pre_request at 0x7f1931b9e430>
2021-09-22T17:57:23.992803+00:00 app[web.1]: post_request: <function PostRequest.post_request at 0x7f1931b9e4c0>
2021-09-22T17:57:23.992803+00:00 app[web.1]: child_exit: <function ChildExit.child_exit at 0x7f1931b9e5e0>
2021-09-22T17:57:23.992803+00:00 app[web.1]: worker_exit: <function WorkerExit.worker_exit at 0x7f1931b9e700>
2021-09-22T17:57:23.992803+00:00 app[web.1]: nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f1931b9e820>
2021-09-22T17:57:23.992804+00:00 app[web.1]: on_exit: <function OnExit.on_exit at 0x7f1931b9e940>
2021-09-22T17:57:23.992804+00:00 app[web.1]: proxy_protocol: False
2021-09-22T17:57:23.992804+00:00 app[web.1]: proxy_allow_ips: ['127.0.0.1']
2021-09-22T17:57:23.992804+00:00 app[web.1]: keyfile: None
2021-09-22T17:57:23.992805+00:00 app[web.1]: certfile: None
2021-09-22T17:57:23.992805+00:00 app[web.1]: ssl_version: 2
2021-09-22T17:57:23.992805+00:00 app[web.1]: cert_reqs: 0
2021-09-22T17:57:23.992805+00:00 app[web.1]: ca_certs: None
2021-09-22T17:57:23.992805+00:00 app[web.1]: suppress_ragged_eofs: True
2021-09-22T17:57:23.992805+00:00 app[web.1]: do_handshake_on_connect: False
2021-09-22T17:57:23.992806+00:00 app[web.1]: ciphers: None
2021-09-22T17:57:23.992806+00:00 app[web.1]: raw_paste_global_conf: []
2021-09-22T17:57:23.992806+00:00 app[web.1]: strip_header_spaces: False
2021-09-22T17:57:23.992961+00:00 app[web.1]: [2021-09-22 17:57:23 +0000] [4] [INFO] Starting 
gunicorn 20.1.0
2021-09-22T17:57:23.993351+00:00 app[web.1]: [2021-09-22 17:57:23 +0000] [4] [DEBUG] Arbiter 
booted
2021-09-22T17:57:23.993388+00:00 app[web.1]: [2021-09-22 17:57:23 +0000] [4] [INFO] Listening at: http://0.0.0.0:43261 (4)
2021-09-22T17:57:23.993428+00:00 app[web.1]: [2021-09-22 17:57:23 +0000] [4] [INFO] Using worker: sync
2021-09-22T17:57:23.996288+00:00 app[web.1]: [2021-09-22 17:57:23 +0000] [8] [INFO] Booting worker with pid: 8
2021-09-22T17:57:24.077444+00:00 app[web.1]: [2021-09-22 17:57:24 +0000] [9] [INFO] Booting worker with pid: 9
2021-09-22T17:57:24.089167+00:00 app[web.1]: [2021-09-22 17:57:24 +0000] [4] [DEBUG] 2 workers
2021-09-22T17:57:24.662522+00:00 app[web.1]: [2021-09-22 17:57:24 +0000] [9] [DEBUG] Closing 
connection.
2021-09-22T17:57:24.667489+00:00 app[web.1]: [2021-09-22 17:57:24 +0000] [9] [DEBUG] Closing 
connection.
2021-09-22T17:57:24.675579+00:00 heroku[web.1]: State changed from starting to up
2021-09-22T17:57:26.675359+00:00 app[web.1]: [2021-09-22 17:57:26 +0000] [8] [DEBUG] GET /   
2021-09-22T17:57:26.684149+00:00 heroku[router]: at=info method=GET path="/" host=article-zone1.herokuapp.com request_id=3267e7aa-29b3-4922-b6d8-91e56242eb8f fwd="49.36.44.18" dyno=web.1 connect=0ms service=11ms status=200 bytes=3067 protocol=https
2021-09-22T17:57:26.685918+00:00 app[web.1]: 10.1.92.204 - - [22/Sep/2021:17:57:26 +0000] "GET / HTTP/1.1" 200 2912 "https://dashboard.heroku.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; 
x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"
2021-09-22T17:57:28.540049+00:00 app[web.1]: [2021-09-22 17:57:28 +0000] [9] [DEBUG] GET /register
2021-09-22T17:57:28.553278+00:00 heroku[router]: at=info method=GET path="/register" host=article-zone1.herokuapp.com request_id=e3ff3e6d-50d4-4626-b04e-f76182e300a0 fwd="49.36.44.18" dyno=web.1 connect=0ms service=15ms status=200 bytes=3481 protocol=https
2021-09-22T17:57:28.555017+00:00 app[web.1]: 10.1.92.204 - - [22/Sep/2021:17:57:28 +0000] "GET /register HTTP/1.1" 200 3326 "https://article-zone1.herokuapp.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"2021-09-22T17:57:30.000000+00:00 app[api]: Build succeeded
2021-09-22T17:57:38.737772+00:00 app[web.1]: [2021-09-22 17:57:38 +0000] [9] [DEBUG] POST /register
2021-09-22T17:57:39.082656+00:00 heroku[router]: at=info method=POST path="/register" host=article-zone1.herokuapp.com request_id=19f8b057-b9fc-47cc-8c73-08724c51566f fwd="49.36.44.18" dyno=web.1 connect=0ms service=347ms status=500 bytes=463 protocol=https
2021-09-22T17:57:39.083650+00:00 app[web.1]: [2021-09-22 17:57:39,082] ERROR in app: Exception on /register [POST]
2021-09-22T17:57:39.083658+00:00 app[web.1]: Traceback (most recent call last):
2021-09-22T17:57:39.083658+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
2021-09-22T17:57:39.083659+00:00 app[web.1]: response = self.full_dispatch_request()
2021-09-22T17:57:39.083659+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
2021-09-22T17:57:39.083660+00:00 app[web.1]: rv = self.handle_user_exception(e)
2021-09-22T17:57:39.083660+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
2021-09-22T17:57:39.083660+00:00 app[web.1]: rv = self.dispatch_request()
2021-09-22T17:57:39.083660+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
2021-09-22T17:57:39.083661+00:00 app[web.1]: return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2021-09-22T17:57:39.083661+00:00 app[web.1]: File "/app/main.py", line 117, in register      
2021-09-22T17:57:39.083661+00:00 app[web.1]: flash("You are now Registered!","success")      
2021-09-22T17:57:39.083661+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/helpers.py", line 391, in flash
2021-09-22T17:57:39.083662+00:00 app[web.1]: session["_flashes"] = flashes
2021-09-22T17:57:39.083662+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/sessions.py", line 97, in _fail
2021-09-22T17:57:39.083662+00:00 app[web.1]: raise RuntimeError(
2021-09-22T17:57:39.083663+00:00 app[web.1]: RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2021-09-22T17:57:39.084292+00:00 app[web.1]: 10.1.92.204 - - [22/Sep/2021:17:57:39 +0000] "POST /register HTTP/1.1" 500 290 "https://article-zone1.herokuapp.com/register" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"
2021-09-22T17:58:06.041669+00:00 app[web.1]: [2021-09-22 17:58:06 +0000] [9] [DEBUG] Closing 
connection.
2021-09-22T18:00:19.837565+00:00 app[web.1]: [2021-09-22 18:00:19 +0000] [9] [DEBUG] Closing 
connection.
2021-09-22T18:02:33.982449+00:00 app[web.1]: [2021-09-22 18:02:33 +0000] [9] [DEBUG] Closing 
connection.
2021-09-22T18:04:48.126095+00:00 app[web.1]: [2021-09-22 18:04:48 +0000] [9] [DEBUG] Closing 
connection.
2021-09-22T18:07:01.929592+00:00 app[web.1]: [2021-09-22 18:07:01 +0000] [8] [DEBUG] Closing 
connection.
2021-09-22T18:09:16.071165+00:00 app[web.1]: [2021-09-22 18:09:16 +0000] [8] [DEBUG] Closing 
connection.
2021-09-22T18:11:29.880279+00:00 app[web.1]: [2021-09-22 18:11:29 +0000] [8] [DEBUG] Closing 
connection.
2021-09-22T18:13:44.022169+00:00 app[web.1]: [2021-09-22 18:13:44 +0000] [9] [DEBUG] Closing 
connection.
2021-09-22T18:15:58.162441+00:00 app[web.1]: [2021-09-22 18:15:58 +0000] [8] [DEBUG] Closing 
connection.
2021-09-22T18:18:11.979642+00:00 app[web.1]: [2021-09-22 18:18:11 +0000] [8] [DEBUG] Closing 
connection.
2021-09-22T18:20:26.114031+00:00 app[web.1]: [2021-09-22 18:20:26 +0000] [9] [DEBUG] Closing 
connection.
2021-09-22T18:22:39.923553+00:00 app[web.1]: [2021-09-22 18:22:39 +0000] [9] [DEBUG] Closing 
connection.
2021-09-22T18:24:54.068384+00:00 app[web.1]: [2021-09-22 18:24:54 +0000] [9] [DEBUG] Closing 
connection.
2021-09-22T18:27:07.865479+00:00 app[web.1]: [2021-09-22 18:27:07 +0000] [9] [DEBUG] Closing 
connection.
2021-09-22T18:29:22.016106+00:00 app[web.1]: [2021-09-22 18:29:22 +0000] [9] [DEBUG] Closing 
connection.
2021-09-22T18:31:36.156432+00:00 app[web.1]: [2021-09-22 18:31:36 +0000] [8] [DEBUG] Closing connection.
2021-09-22T18:33:49.966494+00:00 app[web.1]: [2021-09-22 18:33:49 +0000] [9] [DEBUG] Closing connection.
2021-09-22T18:33:50.347542+00:00 heroku[web.1]: Idling
2021-09-22T18:33:50.392122+00:00 heroku[web.1]: State changed from up to down
2021-09-22T18:33:51.031547+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2021-09-22T18:33:51.108852+00:00 app[web.1]: [2021-09-22 18:33:51 +0000] [8] [INFO] Worker exiting (pid: 8)
2021-09-22T18:33:51.108886+00:00 app[web.1]: [2021-09-22 18:33:51 +0000] [4] [INFO] Handling signal: term
2021-09-22T18:33:51.108887+00:00 app[web.1]: [2021-09-22 18:33:51 +0000] [9] [INFO] Worker exiting (pid: 9)
2021-09-22T18:33:51.209307+00:00 app[web.1]: [2021-09-22 18:33:51 +0000] [4] [INFO] Shutting down: Master
2021-09-22T18:33:51.372589+00:00 heroku[web.1]: Process exited with status 0
